apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: efsprovisioners.efs.storage.openshift.io
spec:
  group: efs.storage.openshift.io
  names:
    kind: EFSProvisioner
    listKind: EFSProvisionerList
    plural: efsprovisioners
    singular: efsprovisioner
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            managementState:
              type: string
              enum:
                - Managed
                - Unmanaged
                - Removed
            imagePullSpec:
              type: string
            version:
              type: string
            replicas:
              type: integer
              minimum: 1
            storageClassName:
              type: string
            reclaimPolicy:
              type: string
              enum:
                - Delete
                - Retain
            fsid:
              type: string
            region:
              type: string
            basePath:
              type: string
            supplementalGroup:
              type: integer
            gidAllocate:
              type: boolean
            gidMin:
              type: integer
            gidMax:
              type: integer
          required:
            - storageClassName
            - fsid
            - region
  subresources:
    status: {}
