{{- if ( has "storage-operators" .Values.catalog_sources ) }}
#! validate-crd: ./deploy/chart/templates/05-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: storage-operators
  namespace: {{ .Values.catalog_namespace }}
spec:
  sourceType: internal
  configMap: storage-operators
  displayName: Storage Operators
  publisher: Red Hat
{{ end }}
