apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: efs-provisioner-operator.v0.0.1
  namespace: default
  annotations:
    alm-examples: '[{"apiVersion":"efsprovisioner.efs.storage.openshift.io/v1alpha1","kind":"EFSProvisioner","metadata":{"name":"example","namespace":"default"},"spec":{"storageClassName":"aws-efs","basePath":"/"}}]'
spec:
  displayName: AWS EFS Provisioner
  labels:
    olm-owner-enterprise-app: efs-provisioner-operator
    olm-status-descriptors: efs-provisioner-operator.v0.0.1
  description: |
    A dynamic PersistentVolume provisioner for AWS EFS storage.
  keywords: ['efs', 'aws', 'provisioner', 'storage']
  version: 0.0.1
  maturity: alpha
  maintainers:
    - name: Matthew Wong
      email: mawong@redhat.com
  provider:
    name: Red Hat, Inc

  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: efs-provisioner-operator
          rules:
            - apiGroups:
              - efs.storage.openshift.io
              resources:
              - "*"
              verbs:
              - "*"
            - apiGroups:
              - ""
              resources:
              - pods
              - services
              - endpoints
              - persistentvolumeclaims
              - events
              - configmaps
              - secrets
              verbs:
              - "*"
            - apiGroups:
              - apps
              resources:
              - deployments
              - daemonsets
              - replicasets
              - statefulsets
              verbs:
              - "*"
            - apiGroups:
              - ""
              resources:
              - serviceaccounts
              verbs:
              - create
            - apiGroups:
              - ""
              resources:
              - serviceaccounts
              resourceNames:
              - efs-provisioner
              verbs:
              - get
              - update
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - roles
              - rolebindings
              verbs:
              - create
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - roles
              resourceNames:
              - leader-locking-efs-provisioner
              verbs:
              - get
              - update
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - rolebindings
              resourceNames:
              - leader-locking-efs-provisioner
              verbs:
              - get
              - update
            - apiGroups: [""]
              resources: ["endpoints"]
              verbs: ["get", "list", "watch", "create", "update", "patch"]
      clusterPermissions:
        - serviceAccountName: efs-provisioner-operator
          rules:
            - apiGroups:
              - storage.k8s.io
              resources:
              - storageclasses
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - delete
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterroles
              - clusterrolebindings
              verbs:
              - create
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterroles
              resourceNames:
              - efs-provisioner-runner
              verbs:
              - get
              - update
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterrolebindings
              resourceNames:
              - run-efs-provisioner
              verbs:
              - get
              - update
            - apiGroups:
              - ""
              resources:
              - nodes
              verbs:
              - get
            - apiGroups: [""]
              resources: ["persistentvolumes"]
              verbs: ["get", "list", "watch", "create", "delete"]
            - apiGroups: [""]
              resources: ["persistentvolumeclaims"]
              verbs: ["get", "list", "watch", "update"]
            - apiGroups: [""]
              resources: ["events"]
              verbs: ["create", "update", "patch"]
            - apiGroups: ["security.openshift.io"]
              resources: ["securitycontextconstraints"]
              verbs: ["use"]
              resourceNames: ["hostmount-anyuid"]
      deployments:
        - name: efs-provisioner-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: efs-provisioner-operator
            template:
              metadata:
                labels:
                  app: efs-provisioner-operator
              spec:
                serviceAccountName: efs-provisioner-operator
                containers:
                  - name: efs-provisioner-operator
                    image: quay.io/openshift/efs-provisioner-operator
                    ports:
                      - containerPort: 60000
                        name: metrics
                    command:
                      - efs-provisioner-operator
                    imagePullPolicy: IfNotPresent
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: OPERATOR_NAME
                        value: "efs-provisioner-operator"
                      - name: NODE_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
  customresourcedefinitions:
    owned:
      - name: efsprovisioners.efs.storage.openshift.io
        version: v1alpha1
        kind: EFSProvisioner
        displayName: EFS Provisioner
        description: Represents an instance of an EFS provisioner.
        resources:
          - kind: Deployment
            version: v1
          - kind: StorageClass
            version: v1
        specDescriptors:
          - description: FSID
            displayName: FSID
            path: fsid

